name: Deploy to AWS

on:
  push:
    branches:
      - main  # Cambia si tu rama principal es diferente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar el código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Instalar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Instalar Serverless CLI v3 (evita login obligatorio de v4)
      - name: Install Serverless CLI v3
        run: npm install -g serverless@3

      # 4. Verificar versión instalada (para asegurarnos que NO es v4)
      - name: Check Serverless version
        run: serverless --version

      # 5. Instalar dependencias del proyecto
      - name: Install dependencies
        run: npm install

      # 6. Configurar credenciales de AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # cámbiala si usas otra

      # 7. Desplegar con Serverless v3
      - name: Deploy with Serverless
        run: serverless deploy --stage dev
