service: serverless-crud-api

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    DYNAMODB_TABLE: notesTable

functions:
  createNote:
    handler: createNote.handler
    events:
      - http:
          path: notes
          method: post

  getNote:
    handler: getNote.handler
    events:
      - http:
          path: notes/{id}
          method: get

  updateNote:
    handler: updateNote.handler
    events:
      - http:
          path: notes/{id}
          method: put

  deleteNote:
    handler: deleteNote.handler
    events:
      - http:
          path: notes/{id}
          method: delete

resources:
  Resources:
    NotesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: notesTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
