name: Deploy to AWS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 0) eliminar cualquier release cached que pueda ser v4
      - name: Remove cached Serverless releases (safe)
        run: |
          if [ -d "$HOME/.serverless" ]; then
            echo "Removing prior Serverless releases..."
            rm -rf "$HOME/.serverless"
          else
            echo "No prior Serverless releases"
          fi

      # 1) Instalar Serverless v3 explícitamente
      - name: Install Serverless CLI v3
        run: npm install -g serverless@3

      # 2) Verificar versión (DEBUG → must be v3.x)
      - name: Check Serverless version
        run: serverless --version

      - name: Install project deps
        run: npm ci

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy with Serverless (v3)
        run: serverless deploy --stage dev
